### ISSUE TITLE
getVersion函数get请求失败导致回调无法执行

### ISSUE THREAD

**Issue by ghost** [shepherdwind/plum#15]
Welcome to Plum v0.5.2, server is running.
Press key ctrl and c to quit!
config url is 127.0.0.1/config
[plum ]: config file path is /Users/willy/.plum.json

undefined:0

^
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/plum/bin/plum:19:15)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

**Comment by shepherdwind** [comment]
哦，在离线状态，确实可能会有问题。我看下

**Comment by shepherdwind** [comment]
github的raw服务器质改变了
